Ensure userHandlerService is with us when creating the category service
Open-Dataplatform/datacatalog-frontend pull request #21
Opened 2021-09-14 12:28 UTC by KasperDamgaard

2021-09-14 12:30 UTC, KasperDamgaard commented
whoops - wrong branch name, but oh well..

2021-09-15 11:51 UTC, MadsSvejstrup requested changes

2021-09-15 11:51 UTC, MadsSvejstrup commented on src/app/shared/services/category.service.ts
> +              });
Hm i'm not sure I like this solution. It will probably always work, but we're not really waiting for the correct event, so its not that clean and i don't think this is guaranteed to work.

The problem is that we make the getCategoryData call before an event has been emitted on the userHasDataStewardRole subject. Therefore we should make the call inside a subscribe to userHasDataStewardRole$.

2021-09-15 11:53 UTC, MadsSvejstrup commented on src/app/shared/services/category.service.ts
> +              });
Okay i messed up the highlighted lines..

2021-09-15 12:00 UTC, KasperDamgaard commented on src/app/shared/services/category.service.ts
> +              });
Ah, of course.. That makes a ton more sense, you're right.. Will go fix

2021-09-15 12:04 UTC, KasperDamgaard commented on src/app/shared/services/category.service.ts
> +              });
This is more like it now. Also is cleaner and easier to read

2021-09-15 12:21 UTC, MadsSvejstrup commented on src/app/shared/services/category.service.ts
> +              });
Yep that's much better. However now two category API calls are made. It looks like it's only happens immediately after logging in though. This could potentially be fixed by making the userHasDataStewardRole subject default to null instead of false and then filter out null with a pipe like is was done with userLoggedIn before

2021-09-15 12:25 UTC, KasperDamgaard commented on src/app/shared/services/category.service.ts
> +              });
Okay okay - Senior Frontend Developer... 
:D 
I'll take another look

2021-09-20 07:22 UTC, merged