Implemented preview functionality
Open-Dataplatform/datacatalog-frontend pull request #26
Opened 2021-09-29 11:38 UTC by KasperDamgaard

Cannot test it locally since I am blocked by CORS when calling the egress API. I did, however, test the resulting http request with postman, which gives back the expected json payload. So it should work. I copied this payload to the backend as a dummy endpoint and tested it that way.

2021-09-29 11:42 UTC, KasperDamgaard commented
Table looks like this:
![image](https://user-images.githubusercontent.com/3296435/135261505-5f73ddf6-883b-4cf6-ac7b-c80b5c3aab55.png)

and data access pane is altered as such:
![image](https://user-images.githubusercontent.com/3296435/135261587-8cea4e21-fd67-4288-9d55-3ca79571e161.png)

2021-09-29 14:56 UTC, MadsSvejstrup commented
Shouldn't we just start fetching a token when pressing 'preview data' instead of throwing an error if a token has not already been fetched? Having to press multiple buttons in the correct order does not seem very nice.

2021-09-29 14:59 UTC, MadsSvejstrup commented
If i click 'preview data' first and then later press 'get token', then it tries to fetch the preview data when clicking 'preview data' - that's unexpected behavior because that was not the button i pressed

2021-09-29 15:00 UTC, MadsSvejstrup requested changes

2021-09-29 15:00 UTC, MadsSvejstrup commented on src/app/pages/details-page/details-page.component.ts
> +
I don't like this method - if we add another code then we have to remember to update it here as well. I suggest that we extend the DurationResponse with an integer that is the number of minutes. In the backend we already have a method that can convert the code to a TimeSpan. 

If we do this then this method is simply just subtracting the number of minutes in the DurationResponse

2021-09-29 15:00 UTC, MadsSvejstrup commented on src/app/pages/details-page/details-page.component.ts
> +    });
The logic that fetches data from the egress api should definitely be pulled out of the component and put in a service instead.

2021-10-04 08:57 UTC, MadsSvejstrup approved these changes
I think it looks great! 

How does the table behave if there are a lot of columns? Will we be able to scroll sideways then?

2021-10-04 09:04 UTC, merged

2021-10-04 09:05 UTC, KasperDamgaard commented
> I think it looks great!
> 
> How does the table behave if there are a lot of columns? Will we be able to scroll sideways then?

No clue - We'll find out :) - I'd rather do a bugfix on that rather than do too much testing. But I think it might just be squeezed together too much.